# Generated by Django 3.2 on 2022-12-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='Extra_files',
            field=models.ManyToManyField(to='Schools.Extra_file'),
        ),
    ]
