# Generated by Django 3.2 on 2023-01-14 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0002_auto_20221224_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='Added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Specific_extra_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='')),
                ('Assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.assessment')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Schools.student')),
            ],
        ),
    ]
